spring:
  application:
    name: gateway-service
  profiles:
    include: route
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.13:8848
        username: nacos
        password: 123456
server:
  port: 9000