spring:
  cloud:
    gateway:
      routes:
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1