spring:
  application:
    name: order-service
  config:
    import:
      - nacos:mysql.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:redis.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:common.yaml?group=DEFAULT_GROUP&refresh=true
      - nacos:order-service.yaml?group=DEFAULT_GROUP&refresh=true
  cloud:
    nacos:
      config:
        server-addr: ${nacos.address:192.168.1.13}:8848
        username: nacos
        password: 123456