spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 192.168.1.13:8848
      username: nacos
      password: 123456
      config:
        namespace: a993f4ef-e2af-4b78-9364-5c19bf945bab
  config:
    import:
      - nacos:order-service.yaml?refresh=true