spring:
  application:
    name: product-service
  cloud:
    nacos:
      discovery:
        enabled: false
        server-addr: ${nacos.address:192.168.1.13}:8848
        username: nacos
        password: 123456
server:
  port: 9020
dubbo:
  enabled: false
  application:
    name: product-dubbo-service
    qos-enable: false
  registry:
    address: nacos://${nacos.address:192.168.1.13}:8848?username=nacos&password=123456
    register-mode: instance
  protocol:
    name: tri
    port: -1